# Generated by Django 5.0.6 on 2025-09-13 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('altura', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('sprite_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(blank=True, max_length=100, null=True)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Treinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemons', models.ManyToManyField(related_name='treinadores', through='pokedex.Equipe', to='pokedex.pokemon')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='equipe',
            name='treinador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.treinador'),
        ),
        migrations.AlterUniqueTogether(
            name='equipe',
            unique_together={('treinador', 'pokemon')},
        ),
    ]
