# Generated by Django 5.2.6 on 2025-09-12 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('altura', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(blank=True, max_length=100, null=True)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Treinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pokemons', models.ManyToManyField(related_name='treinadores', through='pokedex.Equipe', to='pokedex.pokemon')),
            ],
        ),
        migrations.AddField(
            model_name='equipe',
            name='treinador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.treinador'),
        ),
        migrations.AlterUniqueTogether(
            name='equipe',
            unique_together={('treinador', 'pokemon')},
        ),
    ]
