# Generated by Django 5.2.6 on 2025-09-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_remove_pokemon_id_pokedex_alter_pokemon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='sprite_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
